import React, { useEffect, useMemo, useState } from 'react'

const API = ''
const nav = [
  { key:'dashboard', label:'Dashboard', icon:'◆', desc:'Tổng quan VPS' },
  { key:'health', label:'Health Care', icon:'✚', desc:'Kiểm tra sức khỏe' },
  { key:'sites', label:'Websites', icon:'▦', desc:'Quản lý site' },
  { key:'deploy', label:'Deploy GitHub', icon:'⇧', desc:'Deploy code' },
  { key:'domains', label:'Domains & SSL', icon:'◎', desc:'Domain, SSL' },
  { key:'backups', label:'Backups', icon:'◫', desc:'Sao lưu' },
  { key:'monitor', label:'Monitor', icon:'◷', desc:'Tài nguyên' },
  { key:'logs', label:'Logs', icon:'≡', desc:'Nhật ký' },
  { key:'vps', label:'VPS Tools', icon:'⚙', desc:'Service tools' },
  { key:'cyberpanel', label:'CyberPanel', icon:'CP', desc:'8090 status' },
  { key:'settings', label:'Settings', icon:'◇', desc:'Cài đặt' }
]

function bytes(n){ if(!n && n!==0) return '-'; const u=['B','KB','MB','GB','TB']; let i=0,x=Number(n); while(x>=1024&&i<u.length-1){x/=1024;i++} return `${x.toFixed(i?1:0)} ${u[i]}` }
function uptime(s){ s=Number(s||0); const d=Math.floor(s/86400), h=Math.floor(s%86400/3600), m=Math.floor(s%3600/60); return `${d}d ${h}h ${m}m` }
function cls(status){ return status==='good'||status==='running'||status==='active'?'ok':status==='warning'?'warn':'bad' }

function useApi(){
  const [loading,setLoading]=useState(false)
  async function request(url,opt={}){
    setLoading(true)
    try{
      const res=await fetch(API+url,{credentials:'include',headers:{'Content-Type':'application/json'},...opt})
      const text=await res.text(); let json; try{json=JSON.parse(text)}catch{json={text}}
      if(!res.ok) throw new Error(json.error||text||res.statusText)
      return json
    } finally { setLoading(false) }
  }
  return {request,loading}
}

function Login({onLogin}){
  const {request,loading}=useApi(); const [form,setForm]=useState({username:'admin',password:''}); const [err,setErr]=useState('')
  async function submit(e){e.preventDefault(); setErr(''); try{const j=await request('/api/login',{method:'POST',body:JSON.stringify(form)}); onLogin(j.user)}catch(e){setErr(e.message)}}
  return <div className="loginPage">
    <div className="loginVisual"><div className="orb"></div><h1>Momnz VPS Panel PRO</h1><p>Quản lý VPS, website, domain, deploy GitHub, backup, monitor và CyberPanel trong một dashboard chuyên nghiệp.</p><div className="loginBadges"><span>Ubuntu 24.04</span><span>Docker</span><span>Nginx</span><span>Node.js 20</span></div></div>
    <form className="loginCard" onSubmit={submit}><div className="logoMark">M</div><h2>Đăng nhập quản trị</h2><p>Nhập thông tin đã in sau khi cài VPS.</p><label>Username<input value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>Password<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><button className="primary" disabled={loading}>{loading?'Đang vào...':'Login Panel'}</button>{err&&<div className="alert bad">{err}</div>}</form>
  </div>
}

function Layout({user,onLogout,tab,setTab,children,loading}){
  return <div className="shell">
    <aside className="sidebar"><div className="brand"><div className="brandIcon">M</div><div><b>Momnz Panel</b><small>PRO VPS Manager</small></div></div><div className="navList">{nav.map(n=><button key={n.key} className={tab===n.key?'active':''} onClick={()=>setTab(n.key)}><span>{n.icon}</span><div><b>{n.label}</b><small>{n.desc}</small></div></button>)}</div><div className="sideFoot"><div className="userPill"><b>{user?.username}</b><small>Administrator</small></div><button className="ghost" onClick={onLogout}>Logout</button></div></aside>
    <main className="main"><header className="topbar"><div><h1>{nav.find(n=>n.key===tab)?.label}</h1><p>{nav.find(n=>n.key===tab)?.desc}</p></div><div className="topActions"><span className="liveDot"></span><span>{loading?'Syncing...':'Live'}</span><button onClick={()=>location.reload()} className="soft">Refresh</button></div></header>{children}</main>
  </div>
}
function StatCard({title,value,sub,icon,tone}){return <div className={`stat ${tone||''}`}><div><p>{title}</p><h3>{value}</h3><small>{sub}</small></div><i>{icon}</i></div>}
function Panel({title,children,actions}){return <section className="panel"><div className="panelHead"><h2>{title}</h2><div>{actions}</div></div>{children}</section>}
function Progress({value}){value=Math.max(0,Math.min(100,Number(value)||0));return <div className="progress"><span style={{width:`${value}%`}}></span></div>}
function Empty({text}){return <div className="empty">{text}</div>}

function Dashboard({api}){
  const [data,setData]=useState(null); const [err,setErr]=useState('')
  async function load(){try{setData((await api('/api/dashboard')).stats?await api('/api/dashboard'):null)}catch(e){setErr(e.message)}}
  useEffect(()=>{load()},[])
  if(err) return <div className="alert bad">{err}</div>; if(!data) return <div className="skeletonGrid"><div/><div/><div/><div/></div>
  const h=data.health
  return <div className="gridPage">
    <div className="statsGrid"><StatCard title="Websites" value={data.stats.sites} sub={`${data.stats.runningSites} đang chạy`} icon="▦"/><StatCard title="Backups" value={data.stats.backups} sub="Bản sao lưu" icon="◫"/><StatCard title="CPU" value={`${h.cpuPercent}%`} sub={`${h.cpus} cores`} icon="◷" tone={h.cpuPercent>80?'danger':''}/><StatCard title="RAM" value={`${h.memory.percent}%`} sub={`${bytes(h.memory.used)} / ${bytes(h.memory.total)}`} icon="▣" tone={h.memory.percent>80?'danger':''}/></div>
    <div className="twoCol"><Panel title="VPS Health Summary"><div className="healthRows"><div><b>Hostname</b><span>{h.hostname}</span></div><div><b>Uptime</b><span>{uptime(h.uptime)}</span></div><div><b>Disk</b><span>{h.disk.percent} used</span></div><Progress value={parseInt(h.disk.percent)}/><div><b>Nginx</b><span className={`badge ${cls(h.services.nginx)}`}>{h.services.nginx}</span></div><div><b>Docker</b><span className={`badge ${cls(h.services.docker)}`}>{h.services.docker}</span></div><div><b>Mini Panel</b><span className={`badge ${cls(h.services.miniPanel)}`}>{h.services.miniPanel}</span></div></div></Panel>
    <Panel title="Recent Websites">{data.recentSites?.length? <table><thead><tr><th>Name</th><th>Type</th><th>Status</th><th>URL</th></tr></thead><tbody>{data.recentSites.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.type}</td><td><span className={`badge ${cls(s.status)}`}>{s.status}</span></td><td>{s.domain||`:${s.port}`}</td></tr>)}</tbody></table>:<Empty text="Chưa có website. Vào Deploy GitHub để tạo site."/>}</Panel></div>
    <Panel title="Quick Actions"><div className="quick"><button onClick={()=>location.hash='deploy'}>Deploy GitHub</button><button onClick={()=>location.hash='backups'}>Create Backup</button><button onClick={load}>Refresh Health</button><button onClick={()=>window.open('/health','_blank')}>Open /health</button></div></Panel>
  </div>
}
function HealthCare({api}){const [data,setData]=useState(null); useEffect(()=>{api('/api/healthcare').then(setData)},[]); if(!data)return <div className="skeletonGrid"><div/><div/><div/></div>; return <div className="gridPage"><div className="checkGrid">{data.checks.map(c=><div className={`check ${c.status}`} key={c.name}><div><b>{c.name}</b><span>{c.value}</span></div><p>{c.hint}</p></div>)}</div><Panel title="Chi tiết tài nguyên"><pre>{JSON.stringify(data.health,null,2)}</pre></Panel></div>}
function Sites({api}){const [sites,setSites]=useState([]),[log,setLog]=useState(''); async function load(){setSites((await api('/api/sites')).sites||[])} useEffect(()=>{load()},[]); async function action(name,a){await api(`/api/sites/${name}/${a}`,{method:'POST'}); load()} async function del(name){if(confirm('Xóa site và container?')){await api(`/api/sites/${name}`,{method:'DELETE'}); load()}} async function logs(name){setLog(await fetch(`/api/sites/${name}/logs`,{credentials:'include'}).then(r=>r.text()))} return <div className="gridPage"><Panel title="Website Manager" actions={<button onClick={load}>Refresh</button>}>{sites.length?<table><thead><tr><th>Site</th><th>Type</th><th>Status</th><th>Port</th><th>Domain</th><th>Actions</th></tr></thead><tbody>{sites.map(s=><tr key={s.id}><td><b>{s.name}</b><small>{s.repoUrl}</small></td><td>{s.type}</td><td><span className={`badge ${cls(s.status)}`}>{s.status}</span></td><td>{s.port?`:${s.port}`:'-'}</td><td>{s.domain||'-'}</td><td className="actions"><button onClick={()=>action(s.name,'start')}>Start</button><button onClick={()=>action(s.name,'stop')}>Stop</button><button onClick={()=>logs(s.name)}>Logs</button><button className="danger" onClick={()=>del(s.name)}>Delete</button></td></tr>)}</tbody></table>:<Empty text="Chưa có website."/>}</Panel>{log&&<Panel title="Container Logs"><pre>{log}</pre></Panel>}</div>}
function Deploy({api}){const [form,setForm]=useState({name:'',repoUrl:'',domain:'',envText:''}); const [out,setOut]=useState(null); const [loading,setLoading]=useState(false); async function submit(e){e.preventDefault();setLoading(true);setOut(null);try{setOut(await api('/api/deploy',{method:'POST',body:JSON.stringify(form)}))}catch(e){setOut({ok:false,error:e.message})}finally{setLoading(false)}} return <div className="twoCol wideLeft"><Panel title="Deploy GitHub Website"><form className="form" onSubmit={submit}><label>Site name<input placeholder="my-shop" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>GitHub repo HTTPS<input placeholder="https://github.com/user/repo" value={form.repoUrl} onChange={e=>setForm({...form,repoUrl:e.target.value})}/></label><label>Domain optional<input placeholder="example.com đã trỏ A record về VPS" value={form.domain} onChange={e=>setForm({...form,domain:e.target.value})}/></label><label>ENV optional<textarea rows="8" placeholder={'APP_ENV=production\nDATABASE_URL=...'} value={form.envText} onChange={e=>setForm({...form,envText:e.target.value})}/></label><button className="primary" disabled={loading}>{loading?'Đang deploy, chờ build Docker...':'Deploy Now'}</button></form></Panel><Panel title="Deploy Result / Guide"><p className="muted">Panel sẽ clone repo, detect Static/Node/Laravel, build Docker image, chạy container, lưu trạng thái và nếu có domain thì tạo nginx reverse proxy.</p>{out&&<pre>{JSON.stringify(out,null,2)}</pre>}</Panel></div>}
function Domains({api}){const [sites,setSites]=useState([]),[domains,setDomains]=useState([]),[form,setForm]=useState({domain:'',siteName:''}),[out,setOut]=useState(null); async function load(){setSites((await api('/api/sites')).sites||[]);setDomains((await api('/api/domains')).domains||[])} useEffect(()=>{load()},[]); async function add(e){e.preventDefault();try{setOut(await api('/api/domains',{method:'POST',body:JSON.stringify(form)}));load()}catch(e){setOut({ok:false,error:e.message})}} async function ssl(d){setOut(await api(`/api/domains/${d}/ssl`,{method:'POST'}))} return <div className="twoCol"><Panel title="Add Domain"><form onSubmit={add} className="form"><label>Domain<input value={form.domain} onChange={e=>setForm({...form,domain:e.target.value})}/></label><label>Website<select value={form.siteName} onChange={e=>setForm({...form,siteName:e.target.value})}><option value="">Select site</option>{sites.map(s=><option key={s.name}>{s.name}</option>)}</select></label><button className="primary">Add Domain Proxy</button></form><div className="note">SSL thật chỉ chạy khi domain đã trỏ A record về IP VPS. IP trần không cấp Let's Encrypt.</div></Panel><Panel title="Domains">{domains.length?<table><tbody>{domains.map(d=><tr key={d.id}><td>{d.domain}</td><td>{d.siteName}</td><td><button onClick={()=>ssl(d.domain)}>Issue SSL</button></td></tr>)}</tbody></table>:<Empty text="Chưa có domain"/>}{out&&<pre>{JSON.stringify(out,null,2)}</pre>}</Panel></div>}
function Backups({api}){const [list,setList]=useState([]),[out,setOut]=useState(null); async function load(){setList((await api('/api/backups')).backups||[])} useEffect(()=>{load()},[]); async function create(){setOut(await api('/api/backups',{method:'POST'}));load()} return <div className="gridPage"><Panel title="Backup Center" actions={<button className="primary" onClick={create}>Create Full Backup</button>}>{list.length?<table><thead><tr><th>File</th><th>Size</th><th>Date</th></tr></thead><tbody>{list.map(b=><tr key={b.name}><td>{b.name}</td><td>{bytes(b.size)}</td><td>{String(b.createdAt).slice(0,19)}</td></tr>)}</tbody></table>:<Empty text="Chưa có backup"/>}</Panel>{out&&<Panel title="Result"><pre>{JSON.stringify(out,null,2)}</pre></Panel>}</div>}
function Monitor({api}){const [data,setData]=useState(null); useEffect(()=>{api('/api/monitor').then(setData)},[]); if(!data)return <div className="skeletonGrid"><div/><div/><div/></div>; const h=data.health; return <div className="gridPage"><div className="statsGrid"><StatCard title="CPU" value={`${h.cpuPercent}%`} sub={`${h.cpus} cores`} icon="CPU"/><StatCard title="RAM" value={`${h.memory.percent}%`} sub={bytes(h.memory.free)+' free'} icon="RAM"/><StatCard title="Disk" value={h.disk.percent} sub={bytes(h.disk.free)+' free'} icon="SSD"/><StatCard title="Updates" value={h.updates} sub="apt packages" icon="APT"/></div><Panel title="Docker Containers"><table><thead><tr><th>Name</th><th>Image</th><th>Status</th><th>Ports</th></tr></thead><tbody>{data.containers.map((c,i)=><tr key={i}><td>{c.Names}</td><td>{c.Image}</td><td>{c.Status}</td><td>{c.Ports}</td></tr>)}</tbody></table></Panel></div>}
function Logs({api}){const [logs,setLogs]=useState([]),[name,setName]=useState('system'),[text,setText]=useState(''); async function loadList(){setLogs(['system',...((await api('/api/logs')).logs||[])])} async function load(n=name){setName(n); setText(await fetch(`/api/logs/${n}`,{credentials:'include'}).then(r=>r.text()))} useEffect(()=>{loadList().then(()=>load('system'))},[]); return <div className="twoCol sideSmall"><Panel title="Log Files"><div className="listBtns">{logs.map(l=><button className={name===l?'active':''} onClick={()=>load(l)} key={l}>{l}</button>)}</div></Panel><Panel title={`Viewing: ${name}`} actions={<button onClick={()=>navigator.clipboard.writeText(text)}>Copy</button>}><pre>{text}</pre></Panel></div>}
function VpsTools({api}){const [out,setOut]=useState(''); async function act(a){const r=await api('/api/vps/action',{method:'POST',body:JSON.stringify({action:a})});setOut(JSON.stringify(r,null,2))} async function proc(){const r=await api('/api/vps/processes');setOut(r.output)} return <div className="gridPage"><Panel title="VPS Service Actions"><div className="quick"><button onClick={()=>act('restartNginx')}>Restart Nginx</button><button onClick={()=>act('restartDocker')}>Restart Docker</button><button onClick={()=>act('restartPanel')}>Restart Panel</button><button onClick={()=>act('cleanDocker')}>Docker Prune</button><button onClick={proc}>Top Processes</button></div></Panel><Panel title="Output"><pre>{out}</pre></Panel></div>}
function CyberPanel({api}){const [data,setData]=useState(null),[logs,setLogs]=useState(''); async function load(){setData((await api('/api/cyberpanel/status')).cyberpanel)} useEffect(()=>{load()},[]); async function act(a){await api(`/api/cyberpanel/${a}`,{method:'POST'});load()} async function getLogs(){setLogs(await fetch('/api/cyberpanel/logs',{credentials:'include'}).then(r=>r.text()))} if(!data)return <div className="skeletonGrid"><div/></div>; return <div className="gridPage"><Panel title="CyberPanel Integration"><div className="cyberHero"><div><h3>{data.installed?'CyberPanel detected':'CyberPanel not detected'}</h3><p>{data.note}</p><a href={data.url} target="_blank">{data.url}</a></div><span className={`badge ${data.port8090?'ok':'bad'}`}>Port 8090 {data.port8090?'online':'offline'}</span></div><div className="quick"><button onClick={()=>act('start')}>Start</button><button onClick={()=>act('restart')}>Restart</button><button onClick={()=>act('stop')}>Stop</button><button onClick={getLogs}>View Logs</button></div><pre>{JSON.stringify(data,null,2)}</pre></Panel>{logs&&<Panel title="CyberPanel Logs"><pre>{logs}</pre></Panel>}</div>}
function Settings({api}){const [settings,setSettings]=useState({}),[out,setOut]=useState(null); useEffect(()=>{api('/api/settings').then(j=>setSettings(j.settings||{}))},[]); async function save(){setOut(await api('/api/settings',{method:'POST',body:JSON.stringify(settings)}))} return <div className="twoCol"><Panel title="Panel Settings"><div className="form"><label>Panel name<input value={settings.panelName||''} onChange={e=>setSettings({...settings,panelName:e.target.value})}/></label><label>Next site port<input value={settings.nextSitePort||4100} onChange={e=>setSettings({...settings,nextSitePort:Number(e.target.value)})}/></label><label>Theme<select value={settings.theme||'blue'} onChange={e=>setSettings({...settings,theme:e.target.value})}><option>blue</option><option>violet</option><option>emerald</option></select></label><button className="primary" onClick={save}>Save Settings</button></div></Panel><Panel title="Security Notes"><ul className="notes"><li>Không mở database public nếu không cần.</li><li>Let’s Encrypt cần domain thật, không cấp SSL cho IP.</li><li>Backup định kỳ trước khi update.</li><li>Mật khẩu lưu tại /opt/mini-cpanel/data/env chmod 600.</li></ul>{out&&<pre>{JSON.stringify(out,null,2)}</pre>}</Panel></div>}

export default function App(){
  const {request,loading}=useApi(); const [user,setUser]=useState(null); const [tab,setTab]=useState('dashboard')
  useEffect(()=>{request('/api/me').then(j=>setUser(j.user)).catch(()=>{})},[])
  useEffect(()=>{const on=()=>{const h=location.hash.replace('#',''); if(nav.some(n=>n.key===h))setTab(h)}; on(); addEventListener('hashchange',on); return()=>removeEventListener('hashchange',on)},[])
  async function logout(){await request('/api/logout',{method:'POST'}); location.reload()}
  if(!user) return <Login onLogin={setUser}/>
  const api=request
  return <Layout user={user} onLogout={logout} tab={tab} setTab={(t)=>{location.hash=t;setTab(t)}} loading={loading}>
    {tab==='dashboard'&&<Dashboard api={api}/>} {tab==='health'&&<HealthCare api={api}/>} {tab==='sites'&&<Sites api={api}/>} {tab==='deploy'&&<Deploy api={api}/>} {tab==='domains'&&<Domains api={api}/>} {tab==='backups'&&<Backups api={api}/>} {tab==='monitor'&&<Monitor api={api}/>} {tab==='logs'&&<Logs api={api}/>} {tab==='vps'&&<VpsTools api={api}/>} {tab==='cyberpanel'&&<CyberPanel api={api}/>} {tab==='settings'&&<Settings api={api}/>} 
  </Layout>
}
